# Generated by Django 3.2.4 on 2021-06-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('CELL', 'CELL'), ('DATALOGGER', 'DATALOGGER'), ('NODE', 'NODE')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
