# Generated by Django 3.2.4 on 2021-06-10 13:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210610_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, choices=[('HMI', 'HMI'), ('WWI', 'WWI'), ('STR', 'STR'), ('XLS', 'XLS')], max_length=3, null=True)),
                ('type', models.CharField(choices=[('CELL', 'CELL'), ('DATALOGGER', 'DATALOGGER'), ('NODE', 'NODE')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NodeAttributes',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('svalue', models.CharField(blank=True, max_length=255, null=True)),
                ('fvalue', models.FloatField(blank=True, null=True)),
                ('dupdate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('quality', models.CharField(blank=True, choices=[('GOOD', 'GOOD'), ('BAD', 'BAD'), ('UNKNOWN', 'UNKNOWN'), ('SUSPECT', 'SUSPECT')], default='unknown', max_length=7, null=True)),
                ('attributes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes_attributes_ids', to='api.attribute')),
                ('nodes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes_attributes_ids', to='api.node')),
            ],
        ),
    ]
