# Generated by Django 3.2.4 on 2021-06-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_attribute_nodeattributes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NodeAttributes',
            new_name='NodeAttribute',
        ),
    ]
