# Generated by Django 3.2.4 on 2021-06-10 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210610_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeattribute',
            name='nodes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes_attributes', to='api.node'),
        ),
    ]
